from typing import Any, List, Sequence, Tuple, overload

import numpy as np
from typing_extensions import Literal, Protocol

from .structures import Attributes, Coordinate, ExpLoop, FrameMetadata, Metadata

class ND2Reader:
    path: str
    _is_legacy: bool
    def __init__(self, path: str) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def is_open(self) -> bool: ...
    def __enter__(self) -> ND2Reader: ...
    def __exit__(self, *args: Any) -> None: ...
    def attributes(self) -> Attributes: ...
    def metadata(self) -> dict: ...
    def experiment(self) -> List[ExpLoop]: ...
    def text_info(self) -> dict: ...
    def seq_count(self) -> int: ...
    def coord_size(self) -> int: ...
    def coord_info(self) -> List[Coordinate]: ...
    def seq_index_from_coords(self, coords: Sequence[int]) -> int: ...
    def coords_from_seq_index(self, seq_index: int) -> Tuple[int, ...]: ...
    def data(self, seq_index: int = 0) -> np.ndarray: ...
    def _voxel_size(self) -> Tuple[float, float, float]: ...
    def get_stage_coords(self) -> Tuple[Tuple[float, float, float], ...]: ...
    def _zstack_home(self) -> int: ...
    def _custom_data_count(self) -> int: ...
