FROM ubuntu:20.04

RUN apt-get update && apt-get install -y python3-pip

COPY .. nd2

# RUN python3 -m pip install virtualenv
# RUN python3 -m virtualenv /venv
# RUN /venv/bin/pip install nd2

# RUN /venv/bin/python -c 'import nd2;print(nd2.ND2File("b16_pdtB+y50__crop.nd2").sizes)'
